default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Internal Build"
  lane :internal do
    send_progress_message("Build Started :rocket:")
    gradle(task: "clean assembleRelease")

    send_progress_message("Uploading To Internal track :rocket:")
    upload_to_play_store(track: "internal")
  end

  desc "Submit a new Alpha Build"
  lane :alpha do
    send_progress_message("Build Started :rocket:")
    gradle(task: "clean assembleRelease")

    send_progress_message("Uploading To Alpha track :rocket:")
    upload_to_play_store(track: "alpha")
  end

  desc "Submit a new Beta Build"
  lane :beta do
    send_progress_message("Build Started :rocket:")
    gradle(task: "clean assembleRelease")

    send_progress_message("Uploading To Beta track :rocket:")
    upload_to_play_store(track: "beta")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

def send_message(message)
  puts message
end

def send_progress_message(message)
  puts message
end

def on_error(exception)
  send_message "${exception}"
end

after_all do |lane|
  file_name = lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH].gsub(/\/.*\//,"")
  send_message "Successfully deployed new App Update! :champagne:"
  default_payloads = [
      :git_branch,
      :last_git_commit_hash,
      :last_git_commit_message
  ]
  payload = {
      "Build Date" => Time.new.to_s,
      "APK" => file_name
  }
  send_message file_name
  send_message "#{default_payloads}"
  send_message "#{payload}"
end
